### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kumapanda723** [kumapanda723/furima-29255#9]
自身のフリマアプリのURL : https://furima-29255.herokuapp.com/
Basic認証のID : admin
パスワード : 9696
出品者用のメールアドレス : a@a
パスワード : 000000a
購入者用のメールアドレス : b@b
パスワード : 000000b
購入用カードの番号 : 4242424242424242
期限 : 12/23
セキュリティコード : 123

**Comment by keisukekodama** [comment]
提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**・有効な情報を入力しても商品が購入できない。**
issueに記載されているカード情報を記載し、購入しようとしましたが購入できませんでした。
商品を購入できるようにしましょう。

修正し次第、以下の完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません

https://docs.google.com/forms/d/e/1FAIpQLSe08G_NmjDTnmZwvplaR5dUh_zUdqH4B4T60lRDIGpzxqBJAg/viewform

**Comment by kumapanda723** [comment]
ご確認いただきありがとうございます。
ご指摘いただきました項目を修正いたしました。

**Comment by mutorisa** [comment]
髙橋さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by kumapanda723** [comment]
ご確認いただきありがとうございました。
